name: Arduino Lint
on: [push, pull_request]
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4

            -   name: arduino/arduino-lint-action
                uses: arduino/arduino-lint-action@v1.0.2